services:

  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.web.address=:80"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  database:
    image: postgres:16
    profiles:
      - database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${{ secrets.POSTGRES_USER }}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  migrations:
    build: backend
    #command: poetry run alembic upgrade head
    command: >
      /bin/bash -c "
      poetry run alembic upgrade head;
      EXIT_CODE=$?;
      if [ $EXIT_CODE -ne 0 ]; then
        echo 'Alembic migration failed with exit code' $EXIT_CODE;
        exit $EXIT_CODE;
      fi
      "
    volumes:
      - "/home/root_man/.config/dev.community_events.resonite.toml:/app/config.toml"
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - manager
      - client

  signals_manager:
    build: backend
    restart: always
    command: poetry run signals_manager
    profiles:
      - manager
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    volumes:
      - "/home/root_man/.config/dev.community_events.resonite.toml:/app/config.toml"

  api_client:
    build: backend
    restart: always
    profiles:
      - client
    command: poetry run api_client
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    volumes:
      - "/home/root_man/.config/dev.community_events.resonite.toml:/app/config.toml"
    ports:
      - '8000:8000'
    labels:
      - traefik.enable=true

      # Modern API route
      - traefik.http.routers.api_client.rule=Host(`dev.resonite-communities.com`) && PathPrefix(`/api`)
      - traefik.http.routers.api_client.entrypoints=web

      # Private events legacy API route
      - traefik.http.routers.api_client_legacy_private.rule=Host(`adult.dev.resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.api_client_legacy_private.entrypoints=web

      # Public events legacy API route
      - traefik.http.routers.api_client_legacy_public.rule=Host(`dev.resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.api_client_legacy_public.entrypoints=web

  web_client:
    build: backend
    restart: always
    profiles:
      - client
    command: poetry run web_client
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    volumes:
      - "/home/root_man/.config/dev.community_events.resonite.toml:/app/config.toml"
    ports:
      - '8001:8001'
    labels:
      - traefik.enable=true
      - traefik.http.routers.web_client.rule=Host(`dev.resonite-communities.com`)
      - traefik.http.routers.web_client.entrypoints=web

  mkdocs:
    image: squidfunk/mkdocs-material
    working_dir: /docs
    volumes:
      - ./backend/:/docs
    ports:
      - "8002:8000"
    profiles:
      - doc
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.docs.rule=Host(`docs.dev.resonite-communities.com`)
      - traefik.http.routers.docs.entrypoints=web

  cache:
    image: redis:7.0-alpine
    restart: always
    command: redis-server --save ""

volumes:
  postgres_data:
    driver: local