services:

  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.web.address=:80"
      - "--accesslog=true"
    ports:
      - "81:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  database:
    image: postgres:16
    profiles:
      - database
    restart: unless-stopped
    ports:
      - 5433:5432
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user)"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  migrations:
    build: backend
    command: >
      /bin/bash -c "
      poetry run alembic upgrade head;
      EXIT_CODE=$?;
      if [ $EXIT_CODE -ne 0 ]; then
        echo 'Alembic migration failed with exit code' $EXIT_CODE;
        exit $EXIT_CODE;
      fi
      "
    volumes:
      - "/home/root_man/.config/prod.community_events.resonite.toml:/app/config.toml"
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - manager
      - client

  signals_manager:
    build: backend
    restart: always
    command: poetry run signals_manager
    profiles:
      - manager
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    volumes:
      - "/home/root_man/.config/prod.community_events.resonite.toml:/app/config.toml"

  api_client:
    build: backend
    restart: always
    profiles:
      - client
    command: poetry run api_client
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    volumes:
      - "/home/root_man/.config/prod.community_events.resonite.toml:/app/config.toml"
    ports:
      - '9000:8000'
    labels:
      - traefik.enable=true

      # Modern API route
      - traefik.http.routers.prod_api_client.rule=Host(`resonite-communities.com`) && PathPrefix(`/api`)
      - traefik.http.routers.prod_api_client.entrypoints=web

      # Private events legacy API route
      - traefik.http.routers.prod_api_client_legacy_private.rule=Host(`adult.resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.prod_api_client_legacy_private.entrypoints=web

      # Private events legacy API route 2
      - traefik.http.routers.prod_api_client_legacy_private2.rule=Host(`adult-events.resonite.boltwolf.net`) && PathPrefix(`/v1`)
      - traefik.http.routers.prod_api_client_legacy_private2.entrypoints=web

      # Public events legacy API route
      - traefik.http.routers.prod_api_client_legacy_public.rule=Host(`resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.prod_api_client_legacy_public.entrypoints=web

      # Public events legacy API route 2
      - traefik.http.routers.prod_api_client_legacy_public2.rule=Host(`events.resonite.boltwolf.net`) && PathPrefix(`/v1`)
      - traefik.http.routers.prod_api_client_legacy_public2.entrypoints=web


  web_client:
    build: backend
    restart: always
    profiles:
      - client
    command: poetry run web_client
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    volumes:
      - "/home/root_man/.config/prod.community_events.resonite.toml:/app/config.toml"
    ports:
      - '9001:8001'
    labels:
      - traefik.enable=true
      - traefik.http.routers.prod_web_client.rule=Host(`resonite-communities.com`)
      - traefik.http.routers.prod_web_client.entrypoints=web

      # Private events legacy API route 2
      - traefik.http.routers.prod_web_client_legacy_public.rule=Host(`events.resonite.boltwolf.net`)
      - traefik.http.routers.prod_web_client_legacy_public.entrypoints=web

  mkdocs:
    image: squidfunk/mkdocs-material
    working_dir: /docs
    volumes:
      - ./backend/:/docs
    ports:
      - "9002:8000"
    profiles:
      - doc
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.prod_docs.rule=Host(`docs.resonite-communities.com`)
      - traefik.http.routers.prod_docs.entrypoints=web

  cache:
    image: redis:7.0-alpine
    restart: always
    command: redis-server --save ""

secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
  postgres_user:
    environment: POSTGRES_USER
  postgres_db:
    environment: POSTGRES_DB

volumes:
  postgres_data:
    driver: local