# Resonite Events bot
DISCORD_BOT_TOKEN = "ChangeMe"

# Resonite AD Events bot
AD_DISCORD_BOT_TOKEN = "ChangeMe"

REFRESH_INTERVAL = 2

CLOUDVAR_RESONITE_USER = "ChangeMe"
CLOUDVAR_RESONITE_PASS = "ChangeMe"
CLOUDVAR_BASE_NAME = "ChangeMe"
CLOUDVAR_GENERAL_NAME = "All"

SECRET_KEY = "ChangeMe"

FACET_URL = 'ChangeMe'

SECRET = 'ChangeMe'

[Discord]
client_bot_token = "ChangeMe"
[Discord.client]
id = 100000000000000000
secret = "ChangeMe"
redirect_uri = "http://localhost:8000/auth/callback"

[Twitch]
client_id = "ChangeMe"
secret = "ChangeMe"
streams = [
    'resoniteapp',
]
game_id = '1184012414'
account_name = 'ResoniteApp'

[[SIGNALS.DiscordEventsCollector]]
external_id = 100000000000000000
name = "My Discord Community"
description = "A community of people who love to chat and play games together."
url = "https://www.discord.gg/my-community"
tags = ['sfw']
