services:

  database:
    image: postgres:16
    profiles:
      - database
    restart: unless-stopped
    ports:
      - 5432:5432
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user)"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  migrations:
    build: .
    command: >
      /bin/bash -c "
      poetry run alembic upgrade head;
      EXIT_CODE=$?;
      if [ $EXIT_CODE -ne 0 ]; then
        echo 'Alembic migration failed with exit code' $EXIT_CODE;
        exit $EXIT_CODE;
      fi
      "
    secrets:
      - database_url
      - discord_secret
      - secret
      - secret_key
      - sentry_dsn
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DISCORD_SECRET_FILE=/run/secrets/discord_secret
      - SECRET_FILE=/run/secrets/secret
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn
      - CACHE_URL=${CACHE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URL=${DISCORD_REDIRECT_URL}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - manager
      - client

  signals_manager:
    build: .
    restart: always
    command: poetry run signals_manager
    profiles:
      - manager
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    secrets:
      - database_url
      - discord_secret
      - secret
      - secret_key
      - sentry_dsn
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DISCORD_SECRET_FILE=/run/secrets/discord_secret
      - SECRET_FILE=/run/secrets/secret
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn
      - CACHE_URL=${CACHE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URL=${DISCORD_REDIRECT_URL}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}

  api_client:
    build: .
    restart: always
    profiles:
      - client
    command: poetry run api_client
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    ports:
      - '8000:8000'
    secrets:
      - database_url
      - discord_secret
      - secret
      - secret_key
      - sentry_dsn
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DISCORD_SECRET_FILE=/run/secrets/discord_secret
      - SECRET_FILE=/run/secrets/secret
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn
      - CACHE_URL=${CACHE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URL=${DISCORD_REDIRECT_URL}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
    labels:
      - traefik.enable=true

      # Modern API route
      - traefik.http.routers.dev_api_v1_client.rule=Host(`dev.resonite-communities.com`) && PathPrefix(`/api`)
      - traefik.http.routers.dev_api_v1_client.entrypoints=web

      # Private events legacy API v1 route
      - traefik.http.routers.dev_api_v1_client_legacy_private.rule=Host(`adult.dev.resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.dev_api_v1_client_legacy_private.entrypoints=web

      # Private events legacy API v1 route
      - traefik.http.routers.dev_api_v1_client_legacy_private2.rule=Host(`3rd.adult.dev.resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.dev_api_v1_client_legacy_private2.entrypoints=web

      # Public events legacy API v1 route
      - traefik.http.routers.dev_api_v1_client_legacy_public.rule=Host(`dev.resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.dev_api_v1_client_legacy_public.entrypoints=web

      # Public events legacy API v1 route
      - traefik.http.routers.dev_api_v1_client_legacy_public2.rule=Host(`3rd.dev.resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.dev_api_v1_client_legacy_public2.entrypoints=web

      # Public events legacy API V2 route
      - traefik.http.routers.dev_api_v2_client_legacy_public.rule=Host(`dev.resonite-communities.com`) && PathPrefix(`/v2`)
      - traefik.http.routers.dev_api_v2_client_legacy_public.entrypoints=web

  web_client:
    build: .
    restart: always
    profiles:
      - client
    command: poetry run web_client
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    ports:
      - '8001:8001'
    secrets:
      - database_url
      - discord_secret
      - secret
      - secret_key
      - sentry_dsn
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DISCORD_SECRET_FILE=/run/secrets/discord_secret
      - SECRET_FILE=/run/secrets/secret
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn
      - CACHE_URL=${CACHE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URL=${DISCORD_REDIRECT_URL}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.dev_web_client.rule=Host(`dev.resonite-communities.com`)
      - traefik.http.routers.dev_web_client.entrypoints=web

      # Public events legacy API route
      - traefik.http.routers.dev_web_client_legacy_public.rule=Host(`3rd.dev.resonite-communities.com`)
      - traefik.http.routers.dev_web_client_legacy_public.entrypoints=web

  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    ports:
      - "8002:8000"
    profiles:
      - doc
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.dev_docs.rule=Host(`docs.dev.resonite-communities.com`)
      - traefik.http.routers.dev_docs.entrypoints=web

secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
  postgres_user:
    environment: POSTGRES_USER
  postgres_db:
    environment: POSTGRES_DB
  database_url:
    environment: DATABASE_URL
  discord_secret:
    environment: DISCORD_SECRET
  secret:
    environment: SECRET
  secret_key:
    environment: SECRET_KEY
  sentry_dsn:
    environment: SENTRY_DSN

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: dev_community_network
    external: true
