services:

  database_official:
    image: postgres:16
    profiles:
      - database
    restart: unless-stopped
    ports:
      - 5435:5432
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user)"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - shared_backend_network

  migrations_official:
    build: ../..
    command: >
      /bin/bash -c "
      poetry run alembic upgrade head;
      EXIT_CODE=$?;
      if [ $EXIT_CODE -ne 0 ]; then
        echo 'Alembic migration failed with exit code' $EXIT_CODE;
        exit $EXIT_CODE;
      fi
      "
    secrets:
      - database_url
      - discord_secret
      - secret
      - secret_key
      - sentry_dsn
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DISCORD_SECRET_FILE=/run/secrets/discord_secret
      - SECRET_FILE=/run/secrets/secret
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn
      - CACHE_URL=${CACHE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URL=${DISCORD_REDIRECT_URL}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
    depends_on:
      database_official:
        condition: service_healthy
    profiles:
      - manager
      - client
    networks:
      - shared_backend_network

  signals_manager_official:
    build: ../..
    restart: always
    command: poetry run signals_manager
    profiles:
      - manager
    depends_on:
      migrations_official:
        condition: service_completed_successfully
      database_official:
        condition: service_healthy
    secrets:
      - database_url
      - discord_secret
      - secret
      - secret_key
      - sentry_dsn
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DISCORD_SECRET_FILE=/run/secrets/discord_secret
      - SECRET_FILE=/run/secrets/secret
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn
      - CACHE_URL=${CACHE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URL=${DISCORD_REDIRECT_URL}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
    networks:
      - shared_backend_network

  api_client_official:
    build: ../..
    restart: always
    profiles:
      - client
    command: poetry run api_client
    depends_on:
      migrations_official:
        condition: service_completed_successfully
      database_official:
        condition: service_healthy
    ports:
      - '8100:8000'
    networks:
      - shared_backend_network
    secrets:
      - database_url
      - discord_secret
      - secret
      - secret_key
      - sentry_dsn
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DISCORD_SECRET_FILE=/run/secrets/discord_secret
      - SECRET_FILE=/run/secrets/secret
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn
      - CACHE_URL=${CACHE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URL=${DISCORD_REDIRECT_URL}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
    labels:
      - traefik.enable=true

      # CORS middleware
      - traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Origin=*
      - traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Methods=*
      - traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Headers=*

      # Modern API route
      - traefik.http.routers.api_client_official.rule=Host(`official.dev.resonite-communities.com`) && PathPrefix(`/api`)
      - traefik.http.routers.api_client_official.entrypoints=web,websecure
      - traefik.http.routers.api_client_official.middlewares=cors

      # Public events legacy API v1 route
      - traefik.http.routers.api_v1_client_legacy_public_official.rule=Host(`official.dev.resonite-communities.com`) && PathPrefix(`/v1`)
      - traefik.http.routers.api_v1_client_legacy_public_official.entrypoints=web,websecure
      - traefik.http.routers.api_v1_client_legacy_public_official.middlewares=cors

      # Public events legacy API V2 route
      - traefik.http.routers.api_v2_client_legacy_public_official.rule=Host(`official.dev.resonite-communities.com`) && PathPrefix(`/v2`)
      - traefik.http.routers.api_v2_client_legacy_public_official.entrypoints=web,websecure
      - traefik.http.routers.api_v2_client_legacy_public_official.middlewares=cors


  web_client_official:
    build: ../..
    restart: always
    profiles:
      - client
    command: poetry run web_client
    depends_on:
      migrations_official:
        condition: service_completed_successfully
      database_official:
        condition: service_healthy
    ports:
      - '8101:8001'
    networks:
      - shared_backend_network
    secrets:
      - database_url
      - discord_secret
      - secret
      - secret_key
      - sentry_dsn
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DISCORD_SECRET_FILE=/run/secrets/discord_secret
      - SECRET_FILE=/run/secrets/secret
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn
      - CACHE_URL=${CACHE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_REDIRECT_URL=${DISCORD_REDIRECT_URL}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.dev_web_client_official.rule=Host(`official.dev.resonite-communities.com`)
      - traefik.http.routers.dev_web_client_official.entrypoints=web

secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
  postgres_user:
    environment: POSTGRES_USER
  postgres_db:
    environment: POSTGRES_DB
  database_url:
    environment: DATABASE_URL
  discord_secret:
    environment: DISCORD_SECRET
  secret:
    environment: SECRET
  secret_key:
    environment: SECRET_KEY
  sentry_dsn:
    environment: SENTRY_DSN

volumes:
  postgres_data:
    driver: local

networks:
  shared_backend_network:
    external: true
