"""Add updated_at field to User model

Revision ID: 07ce94ed8861
Revises: a5bff983b147
Create Date: 2025-12-15 06:32:11.844555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07ce94ed8861'
down_revision: Union[str, None] = 'a5bff983b147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###
