"""Add normal user login field

Revision ID: 156f951308db
Revises: 87c423870cc9
Create Date: 2025-08-08 11:20:40.944517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = '156f951308db'
down_revision: Union[str, None] = '87c423870cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('normal_user_login', sa.Boolean(), nullable=True))
    op.execute("UPDATE app_config SET normal_user_login = TRUE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_config', 'normal_user_login')
    # ### end Alembic commands ###
