"""Add community enabled field

Revision ID: 2616ddbd1242
Revises: 8cab0f51a805
Create Date: 2026-04-30 17:11:05.721989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2616ddbd1242'
down_revision: Union[str, None] = 'b4e7f2a1c8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('enabled', sa.Boolean(), nullable=True, server_default="True"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'enabled')
    # ### end Alembic commands ###
