"""Add remote community field

Revision ID: 404c75b378c9
Revises: 88744e39fb7c
Create Date: 2025-08-17 08:13:32.166713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities

from resonite_communities.models.community import CommunityPlatform


# revision identifiers, used by Alembic.
revision: str = '404c75b378c9'
down_revision: Union[str, None] = '88744e39fb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_name = CommunityPlatform.mro()[0].__name__.lower()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('remote', sa.Boolean(), nullable=True))
    op.execute(f"ALTER TYPE {enum_name} ADD VALUE '{CommunityPlatform.JSON_COMMUNITY_EVENT.name}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql = f"""DELETE FROM pg_enum
        WHERE enumlabel = '{CommunityPlatform.JSON_COMMUNITY_EVENT.name}'
        AND enumtypid = (
            SELECT oid FROM pg_type WHERE typname = '{enum_name}'
        )"""
    op.execute(sql)
    op.drop_column('community', 'remote')
    # ### end Alembic commands ###
