"""Option for init app

Revision ID: 45947e603687
Revises: eed8b4f90016
Create Date: 2025-08-14 14:04:25.518968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = '45947e603687'
down_revision: Union[str, None] = 'eed8b4f90016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('initiated', sa.Boolean(), nullable=True))
    op.execute("UPDATE app_config SET initiated = FALSE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_config', 'initiated')
    # ### end Alembic commands ###
