"""split community description

Revision ID: 6a467b98d913
Revises: 740f7817910e
Create Date: 2025-04-07 10:51:02.195718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = '6a467b98d913'
down_revision: Union[str, None] = '740f7817910e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('default_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('community', sa.Column('custom_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('community', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('community', 'custom_description')
    op.drop_column('community', 'default_description')
    # ### end Alembic commands ###
