"""Option all optional

Revision ID: 88744e39fb7c
Revises: 45947e603687
Create Date: 2025-08-14 14:46:23.589713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = '88744e39fb7c'
down_revision: Union[str, None] = '45947e603687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_config', 'discord_bot_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app_config', 'ad_discord_bot_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app_config', 'refresh_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('app_config', 'cloudvar_resonite_user',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app_config', 'cloudvar_resonite_pass',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app_config', 'cloudvar_base_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app_config', 'cloudvar_general_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app_config', 'facet_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_config', 'facet_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_config', 'cloudvar_general_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_config', 'cloudvar_base_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_config', 'cloudvar_resonite_pass',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_config', 'cloudvar_resonite_user',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_config', 'refresh_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('app_config', 'ad_discord_bot_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_config', 'discord_bot_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
