"""Add remote community field

Revision ID: 8a1785ac21ec
Revises: 88744e39fb7c
Create Date: 2025-08-17 16:52:14.938898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities

from resonite_communities.models.community import CommunityPlatform

# revision identifiers, used by Alembic.
revision: str = '8a1785ac21ec'
down_revision: Union[str, None] = '88744e39fb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_name = CommunityPlatform.mro()[0].__name__.lower()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE {enum_name} ADD VALUE '{CommunityPlatform.JSON_COMMUNITY_EVENT.name}'")
    op.add_column('community', sa.Column('platform_on_remote', sa.Enum(CommunityPlatform, native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'platform_on_remote')
    # ### commands auto generated by Alembic - please adjust! ###
    sql = f"""DELETE FROM pg_enum
        WHERE enumlabel = '{CommunityPlatform.JSON_COMMUNITY_EVENT.name}'
        AND enumtypid = (
            SELECT oid FROM pg_type WHERE typname = '{enum_name}'
        )"""
    op.execute(sql)
    # ### end Alembic commands ###
