"""Add languages fields to community

Revision ID: 8cab0f51a805
Revises: 07ce94ed8861
Create Date: 2026-01-30 22:29:23.992435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cab0f51a805'
down_revision: Union[str, None] = '07ce94ed8861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('languages', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'languages')
    # ### end Alembic commands ###
