"""Add client and user_agent metric

Revision ID: d734a13f111c
Revises: de0e9f7abd00
Create Date: 2025-03-01 14:20:54.541591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = 'd734a13f111c'
down_revision: Union[str, None] = 'de0e9f7abd00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    clienttype_enum = sa.Enum('BOT', 'NEOS', 'RESONITE', 'TOOL', 'BROWSER_MOBILE', 'BROWSER_DESKTOP', name='clienttype')
    clienttype_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('metrics', sa.Column('client', clienttype_enum, nullable=True))
    op.add_column('metrics', sa.Column('user_agent', sa.String(), nullable=True))
    op.create_index(op.f('ix_metrics_client'), 'metrics', ['client'], unique=False)
    op.create_index(op.f('ix_metrics_user_agent'), 'metrics', ['user_agent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_user_agent'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_client'), table_name='metrics')
    op.drop_column('metrics', 'user_agent')
    op.drop_column('metrics', 'client')
    # ### end Alembic commands ###
