"""Add version to metrics

Revision ID: de0e9f7abd00
Revises: 9ac1967a147c
Create Date: 2025-02-23 14:30:55.168851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = 'de0e9f7abd00'
down_revision: Union[str, None] = '9ac1967a147c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('version', sa.String(), nullable=True))
    op.create_index(op.f('ix_metrics_version'), 'metrics', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_version'), table_name='metrics')
    op.drop_column('metrics', 'version')
    # ### end Alembic commands ###
