"""Option for theme

Revision ID: eed8b4f90016
Revises: 156f951308db
Create Date: 2025-08-10 18:15:50.658583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = 'eed8b4f90016'
down_revision: Union[str, None] = '156f951308db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('hero_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('app_config', sa.Column('info_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('app_config', sa.Column('footer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('app_config', sa.Column('title_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_config', 'title_text')
    op.drop_column('app_config', 'footer_text')
    op.drop_column('app_config', 'info_text')
    op.drop_column('app_config', 'hero_color')
    # ### end Alembic commands ###
