"""Add metrics

Revision ID: 591df58a806c
Revises: 101730d4316f
Create Date: 2025-02-22 12:16:18.774672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = '591df58a806c'
down_revision: Union[str, None] = '101730d4316f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('hashed_ip', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_domain'), 'metrics', ['domain'], unique=False)
    op.create_index(op.f('ix_metrics_endpoint'), 'metrics', ['endpoint'], unique=False)
    op.create_index(op.f('ix_metrics_hashed_ip'), 'metrics', ['hashed_ip'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_hashed_ip'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_endpoint'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_domain'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
