"""Add country to metrics

Revision ID: 9ac1967a147c
Revises: 591df58a806c
Create Date: 2025-02-22 14:50:32.092994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import fastapi_users_db_sqlalchemy
import resonite_communities


# revision identifiers, used by Alembic.
revision: str = '9ac1967a147c'
down_revision: Union[str, None] = '591df58a806c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('country', sa.String(), nullable=True))
    op.create_index(op.f('ix_metrics_country'), 'metrics', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_country'), table_name='metrics')
    op.drop_column('metrics', 'country')
    # ### end Alembic commands ###
