name: Deploy Prod

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: SANVM07
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Build app
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: docker compose -f prod.docker-compose.yml -p prod_community_eventsresonite --profile "*" build

      - name: Update 3rd party docker images
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: docker compose -f prod.docker-compose.yml -p prod_community_eventsresonite --profile "*" pull

      - name: Spin up containers
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: docker compose -f prod.docker-compose.yml -p prod_community_eventsresonite --profile "*" up -d