name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: SANVM07

    steps:
      - uses: actions/checkout@v3

      - name: Build app
        run: docker compose -f dev.docker-compose.yml -p dev_community_eventsresonite --profile "*" build

      - name: Update 3rd party docker images
        run: docker compose -f dev.docker-compose.yml -p dev_community_eventsresonite --profile "*" pull

      - name: Spin up containers
        run: docker compose -f dev.docker-compose.yml -p dev_community_eventsresonite --profile "*" up -d